<script type="text/javascript">
/* Page init setting for User */
KE.show({
    id : 'content',
    cssPath : '<?= Zend_Registry::get('baseDir')?>/Common/Layout/KindEditor.css'
});
var initUrl = "<?= Zend_Registry::get('baseUrl')?>/notice/query";
var initParam = "currentpage=1";
var columnName = new Array("noticeid", "headline", "creator", "expireddate");
var operate = "edit,delete";
var currentPage = "1";

$(document).ready(function() {
	fillData(initUrl, initParam, columnName, operate, currentPage);
	markDisabled(Array("edit", "createdtime"));
	$("#scope").val("<?= $_SESSION['currentProjectName']?>");
});

/* Fill data to action panel for Edit */
function goEdit(obj, isEdit) {
	var dataRow = $(obj).parent().parent().children();
	var param = "noticeid=" + dataRow.eq(0).text();
	$.post(initUrl, param, function (data) {
		var json = eval(data);
    	var lenJson = json.length - 1;
    	if (lenJson == 1) {
        	$("#noticeid").val(json[0]['noticeid']);
        	$("#headline").val(json[0]['headline']);
        	$("#scope").val(json[0]['scope']);
        	setKEContent('content', json[0]['content']);
        	$("#creator").val(json[0]['creator']);
        	//$("#createdtime").val(json[0]['createdtime']);
        	$("#expireddate").val(json[0]['expireddate']);
    	}
    	else {
        	$("#msg").text("<?= $this->translate('message.common.nodata')?>");
    	}
	});
	if (isEdit) {
		markEnabled(Array("edit"));
		markDisabled(Array("add", "noticeid"));
	}
	else {
		markDisabled(Array("edit"));
		markEnabled(Array("add", "noticeid"));
	}
	$("#msg").text("<?= $this->translate('tip.common.action')?>");
	$("#actionPanel").show();
	location.href = "#top";
}

/* Add new data */
function doAdd() {
    if (isNull("scope")) {
    	$("#msg").text("<?= $this->translate('message.notice.scope.null')?>");
    	return false;
    }
    if (isNull("headline")) {
    	$("#msg").text("<?= $this->translate('message.notice.headline.null')?>");
    	return false;
    }
    if (! isDate("expireddate")) {
		$("#msg").text("<?= $this->translate('message.common.validate.datetime')?>");
		return false;
	}
	var url = "<?= Zend_Registry::get('baseUrl')?>/notice/add";
	var param = "headline=" + $.trim($("#headline").val()) + 
			"&content=" + replaceAmp(KE.util.getData('content')) + 
			"&scope=" + $("#scope").val() + 
			"&expireddate=" + $.trim($("#expireddate").val());
    $.post(url, param, function (data) {
    	switch (data) {
    	case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.add')?>");
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.add.failed')?>" + "Null");
    		break;
    	default:
    		fillData(initUrl, initParam, columnName, operate, currentPage);
    		$("#noticeid").val(data);
    		$("#msg").text("<?= $this->translate('message.common.add.successful')?>" + data);
    	}
    });
}

/* Edit existing data */
function doEdit() {
	if (isNull("scope")) {
    	$("#msg").text("<?= $this->translate('message.notice.scope.null')?>");
    	return false;
    }
	if (isNull("headline")) {
    	$("#msg").text("<?= $this->translate('message.notice.headline.null')?>");
    	return false;
    }
	var noticeid = $.trim($("#noticeid").val());
	var url = "<?= Zend_Registry::get('baseUrl')?>/notice/edit";
	var param = "noticeid=" + noticeid + 
				"&headline=" + $.trim($("#headline").val()) + 
				"&content=" + replaceAmp(KE.util.getData('content')) + 
				"&scope=" + $("#scope").val() +
				"&expireddate=" + $.trim($("#expireddate").val());
    $.post(url, param, function (data) {
    	switch (data) {
    	case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.edit')?>");
    		break;
    	case "1":
    		fillEdit(initUrl, "noticeid=" + noticeid, columnName, noticeid);
    		$("#msg").text("<?= $this->translate('message.common.edit.successful')?>" + $("#noticeid").val());
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.edit.failed')?>" + $("#noticeid").val());
    		break;
        default:
    		$("#msg").text(data);
    	}
	});
}

/* Delete data according to ID */
function doDelete(obj) {
	if(!confirm("<?= $this->translate('message.common.delete.confirm')?>"))
		return false;
	var dataRow = $(obj).parent().parent().children();
	var noticeid = $.trim(dataRow.eq(0).text());
	var url = "<?= Zend_Registry::get('baseUrl')?>/notice/delete";
	var param = "noticeid=" + noticeid;
	$.post(url, param, function(data) {
		switch (data) {
		case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.delete')?>");
    		break;
    	case "1":
    		$("#msg").text("<?= $this->translate('message.common.delete.successful')?>" + noticeid);
			dataRow.remove();
			$("#totalRecord").text($("#totalRecord").text() - 1);
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.delete.failed')?>" + noticeid);
    		break;
    	default:
    		$("#msg").text(data);
    	}
	});
}

/* Search data */
function doSearch(isSearch, currentPage) {
	if (isSearch) {
		$("#cacheDiv").removeData("cacheData");
		var cacheArray = new Array();
		cacheArray['noticeid'] = $.trim($("#noticeid").val());
		cacheArray['headline'] = $.trim($("#headline").val());
		cacheArray['content'] = replaceAmp($.trim(KE.util.getPureData('content')));
		cacheArray['creator'] = $.trim($("#creator").val());
		cacheArray['scope'] = $.trim($("#scope").val());
		cacheArray['expireddate'] = $.trim($("#expireddate").val());
		$("#cacheDiv").data("cacheData", cacheArray);
	}
	var cacheData = $("#cacheDiv").data("cacheData");
	if (typeof(cacheData) == "undefined")
		var param = "currentpage=" + currentPage;
	else
		var param = "currentpage=" + currentPage +
				"&noticeid=" + cacheData['noticeid'] + 
		    	"&headline=" + cacheData['headline'] + 
		    	"&content=" + cacheData['content'] + 
		    	"&creator=" + cacheData['creator'] +
		    	"&scope=" + cacheData['scope'] +
		    	"&expireddate=" + cacheData['expireddate'];
	fillData(initUrl, param, columnName, operate, currentPage);
	$("#msg").text("<?= $this->translate('tip.common.action')?>");
}

/* Reset KE content */
function resetKE() {
	setKEContent("content", "");
}
</script>

<br />
<table class="table-action">
<thead>
<tr>
	<a name="top"></a>
	<td colspan="5">
	    <?= $this->translate('common.page.panel')?>:&nbsp;&nbsp;
	    <label id="hideShow" />
	</td>
</tr>
</thead>
<tbody id="actionPanel">
<tr>
	<td width="14%"><?= $this->translate('column.common.id')?>:</td>
	<td width="36"><input type="text" id="noticeid" class="short" title="<?= $this->translate('tip.common.forsearch')?>" /></td>
	<td width="15%"><?= $this->translate('column.notice.creator')?>:</td>
	<td width="25%" align="right"><input type="text" id="creator" maxlength="30" value="<?= $_SESSION['userName']?>" class="short" title="<?= $this->translate('tip.common.forsearch')?>" /></td>
	<td width="10%"></td>
</tr>
<tr>
	<td><?= $this->translate('column.notice.scope')?>:</td>
	<td>
	<select id="scope" class="short">
		<option value=""></option>
		<option value="0" selected><?= $this->translate('column.notice.allproj')?></option>
		<?php 
		    $myProject = $_SESSION['myProject'];
    	        foreach ($myProject as $value) {
    	            echo '<option value="' , $value['projectid'] , '">' , $value['projname'], '</option>';
    	        }
		?>
	</select>
	</td>
	<td><?= $this->translate('column.notice.expireddate')?>:</td>
	<td align="right"><input type="text" id="expireddate" maxlength="30" value="<?= date('Y-m-d', time() + 3600 * 24 * 90)?>" class="short" onclick="calendar(this, false)" /></td>
	<td></td>
</tr>
<tr>
	<td><?= $this->translate('column.notice.headline')?>:</font></td>
	<td colspan="3"><input type="text" id="headline" maxlength="250" class="long" /></td>
	<td></td>
</tr>
<tr>
	<td><?= $this->translate('column.notice.content')?>:</td>
	<td colspan="3"><textarea id="content"></textarea></td>
	<td></td>
</tr>
</tbody>
<tfoot>
<tr>
	<td><?= $this->translate('common.page.operate')?>:</td>
	<td><span id="actionButton" /></td>
	<td colspan="3">
		<span id="msg" class="message"><?= $this->translate('tip.common.action')?></span>
		<span id="loading" class="loading"><img src="<?= Zend_Registry::get('baseDir')?>/Common/Image/loading.gif" /></span>
	</td>
</tr>
</tfoot>
</table>

<br />
<table class="table-data" id="dataTable">
<thead>
<tr>
    <th width="10%" class="id"><?= $this->translate('column.common.id')?></th>
    <th width="42%"><?= $this->translate('column.notice.headline')?></th>
    <th width="17%"><?= $this->translate('column.notice.creator')?></th>
    <th width="18%"><?= $this->translate('column.notice.expireddate')?></th>
    <th width="13%"><?= $this->translate('column.common.operate')?></th>
</tr>
</thead>
<tbody id="dataPanel"></tbody>
<tfoot id="footer"></tfoot>
</table>