<script type="text/javascript">
/* Page init setting for User */
KE.show({
    id : 'content',
    cssPath : '<?= Zend_Registry::get('baseDir')?>/Common/Layout/KindEditor.css'
});
var initUrl = "<?= Zend_Registry::get('baseUrl')?>/spec/query";
var initParam = "currentpage=1";
var columnName = new Array("specid", "creator", "userstoryid", "type");
var operate = "edit,delete";
var currentPage = "1";

$(document).ready(function() {
	fillData(initUrl, initParam, columnName, operate, currentPage);
	markDisabled(Array("edit"));
	$("#type").attr("selectedIndex", 1);
});

/* Fill data to action panel for Edit */
function goEdit(obj, isEdit) {
	var dataRow = $(obj).parent().parent().children();
	var param = "specid=" + dataRow.eq(0).text();
	$.post(initUrl, param, function (data) {
		var json = eval(data);
    	var lenJson = json.length - 1;
    	if (lenJson == 1) {
        	$("#specid").val(json[0]['specid']);
        	$("#creator").val(json[0]['creator']);
        	$("#userstoryid").val(json[0]['userstoryid']);
        	if (json[0]['userstoryid'] == 0)
        		$("#userstoryid").val('');
        	$("#type").val(json[0]['type']);
        	setKEContent('content', json[0]['content']);
    	}
    	else {
        	$("#msg").text("<?= $this->translate('message.common.nodata')?>");
    	}
	});
	if (isEdit) {
		markEnabled(Array("edit"));
		markDisabled(Array("add", "specid"));
	}
	else {
		markDisabled(Array("edit"));
		markEnabled(Array("add", "specid"));
	}
	$("#msg").text("<?= $this->translate('tip.common.action')?>");
	$("#actionPanel").show();
	location.href = "#top";
}

/* Add new data */
function doAdd() {
	var content = replaceAmp(KE.util.getData('content'));
    if ($.trim(content) == "") {
		$("#msg").text("<?= $this->translate('message.spec.content.null')?>");
		KE.util.focus('content');
		return false;
	}
	var url = "<?= Zend_Registry::get('baseUrl')?>/spec/add";
	var param = "userstoryid=" + $.trim($("#userstoryid").val()) + 
				"&type=" + $.trim($("#type").val()) + 
				"&content=" + content;
    $.post(url, param, function (data) {
    	switch (data) {
    	case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.add')?>");
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.add.failed')?>" + "Null");
    		break;
    	default:
    		fillData(initUrl, initParam, columnName, operate, currentPage);
    		$("#specid").val(data);
    		$("#msg").text("<?= $this->translate('message.common.add.successful')?>" + data);
    	}
    });
}

/* Edit existing data */
function doEdit() {
	var content = replaceAmp(KE.util.getData('content'));
    if ($.trim(content) == "") {
		$("#msg").text("<?= $this->translate('message.spec.content.null')?>");
		KE.util.focus('content');
		return false;
	}
    var specid = $.trim($("#specid").val());
	var url = "<?= Zend_Registry::get('baseUrl')?>/spec/edit";
	var param = "specid=" + specid + 
				"&userstoryid=" + $.trim($("#userstoryid").val()) + 
				"&type=" + $.trim($("#type").val()) + 
				"&content=" + content;
    $.post(url, param, function (data) {
    	switch (data) {
    	case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.edit')?>");
    		break;
    	case "1":
    		fillEdit(initUrl, "specid=" + specid, columnName, specid);
    		$("#msg").text("<?= $this->translate('message.common.edit.successful')?>" + $("#specid").val());
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.edit.failed')?>" + $("#specid").val());
    		break;
        default:
    		$("#msg").text(data);
    	}
	});
}

/* Delete data according to ID */
function doDelete(obj) {
	if(!confirm("<?= $this->translate('message.common.delete.confirm')?>"))
		return false;
	var dataRow = $(obj).parent().parent().children();
	var specid = $.trim(dataRow.eq(0).text());
	url = "<?= Zend_Registry::get('baseUrl')?>/spec/delete";
	param = "specid=" + specid;
	$.post(url, param, function(data) {
		switch (data) {
		case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.delete')?>");
    		break;
    	case "1":
    		$("#msg").text("<?= $this->translate('message.common.delete.successful')?>" + specid);
			dataRow.remove();
			$("#totalRecord").text($("#totalRecord").text() - 1);
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.delete.failed')?>" + specid);
    		break;
    	default:
    		$("#msg").text(data);
    	}
	});
}

/* Search data */
function doSearch(isSearch, currentPage) {
	if (isSearch) {
		$("#cacheDiv").removeData("cacheData");
		var cacheArray = new Array();
		cacheArray['specid'] = $.trim($("#specid").val());
		cacheArray['userstoryid'] = $.trim($("#userstoryid").val());
		cacheArray['creator'] = $.trim($("#creator").val());
		cacheArray['type'] = $.trim($("#type").val());
		cacheArray['content'] = replaceAmp($.trim(KE.util.getPureData('content')));
		$("#cacheDiv").data("cacheData", cacheArray);
	}
	var cacheData = $("#cacheDiv").data("cacheData");
	if (typeof(cacheData) == "undefined")
		var param = "currentpage=" + currentPage;
	else
		var param = "currentpage=" + currentPage +
					"&specid=" + cacheData['specid'] +
			    	"&userstoryid=" + cacheData['userstoryid'] + 
			    	"&creator=" + cacheData['creator'] +
			    	"&type=" + cacheData['type'] +
			    	"&content=" + cacheData['content'];
	fillData(initUrl, param, columnName, operate, currentPage);
	$("#msg").text("<?= $this->translate('tip.common.action')?>");
}

/* Reset KE content */
function resetKE() {
	setKEContent("content", "");
}
</script>

<br />
<table class="table-action">
<thead>
<tr>
	<a name="top"></a>
	<td colspan="5">
	    <?= $this->translate('common.page.panel')?>:&nbsp;&nbsp;
	    <label id="hideShow" />
	</td>
</tr>
</thead>
<tbody id="actionPanel">
<tr>
	<td width="14%"><?= $this->translate('column.common.id')?>:</td>
	<td width="36%"><input type="text" id="specid" class="short" title="<?= $this->translate('tip.common.forsearch')?>" /></td>
	<td width="15%"><?= $this->translate('column.spec.creator')?>:</td>
	<td width="25%" align="right"><input type="text" id="creator" value="<?= $_SESSION['userName']?>" class="short" title="<?= $this->translate('tip.common.forsearch')?>" /></td>
	<td width="10%"></td>
</tr>
<tr>
	<td><?= $this->translate('column.spec.userstory')?>:</td>
	<td>
	<select id="userstoryid" class="short">
		<option value=""></option>
		<?php
		 	$common = new Common();
	        foreach ($this->userstory as $userstory) {
	            if ($userstory['userstoryid'] == $this->userstoryid)
	               echo '<option value="' , $userstory['userstoryid'] , '" selected>' , $userstory['userstoryid'] , ' - ' , $common->subString($userstory['headline'], 26) , '</option>';
	            else 
	                echo '<option value="' , $userstory['userstoryid'] , '">' , $userstory['userstoryid'] , ' - ' , $common->subString($userstory['headline'], 26) , '</option>';
	        }
		?>
	</select>
	</td>
	<td><?= $this->translate('column.spec.type')?>:</td>
	<td align="right">
	<select id="type" class="short">
		<option value=""></option>
			<?php
	        $common = new Common();
	        $tcType = $common->parseDefinition('spec-type');
		    foreach ($tcType as $tt) {
                echo '<option value="' , $tt , '">' , $tt , '</option>';
		    }
	    ?>
	</select>
	</td>
	<td></td>
</tr>
<tr>
	<td><?= $this->translate('column.testcase.content')?>:</td>
	<td colspan="3"><textarea id="content" class="long"></textarea></td>
	<td></td>
</tr>
</tbody>
<tfoot>
<tr>
	<td><?= $this->translate('common.page.operate')?>:</td>
	<td><span id="actionButton" /></td>
	<td colspan="3">
		<span id="msg" class="message"><?= $this->translate('tip.common.action')?></span>
		<span id="loading" class="loading"><img src="<?= Zend_Registry::get('baseDir')?>/Common/Image/loading.gif" /></span>
	</td>
</tr>
</tfoot>
</table>

<br />
<table class="table-data" id="dataTable">
<thead>
<tr>
    <th width="10%" class="id"><?= $this->translate('column.common.id')?></th>
    <th width="25%"><?= $this->translate('column.spec.creator')?></th>
    <th width="20%"><?= $this->translate('column.spec.userstory')?></th>
    <th width="25%"><?= $this->translate('column.spec.type')?></th>
    <th width="20%"><?= $this->translate('column.common.operate')?></th>
</tr>
</thead>
<tbody id="dataPanel"></tbody>
<tfoot id="footer"></tfoot>
</table>