<script type="text/javascript">
/* Page init setting for User */
KE.show({
    id : 'content',
    cssPath : '<?= Zend_Registry::get('baseDir')?>/Common/Layout/KindEditor.css'
});
var initUrl = "<?= Zend_Registry::get('baseUrl')?>/testcase/query";
var initParam = "currentpage=1";
var columnName = new Array("testcaseid", "headline", "creator", "userstoryid", "priority");
var operate = "edit,delete,execute";
var currentPage = "1";

$(document).ready(function() {
	fillData(initUrl, initParam, columnName, operate, currentPage);
	markDisabled(Array("edit", "execute", "history"));
	$("#type").attr("selectedIndex", 3);
	$("#status").attr("selectedIndex", 1);
	$("#priority").attr("selectedIndex", 2);
});

/* Fill data to action panel for Edit */
function goEdit(obj, isEdit) {
	var dataRow = $(obj).parent().parent().children();
	var param = "testcaseid=" + dataRow.eq(0).text();
	$.post(initUrl, param, function (data) {
		var json = eval(data);
    	var lenJson = json.length - 1;
    	if (lenJson == 1) {
        	$("#testcaseid").val(json[0]['testcaseid']);
        	$("#userstoryid").val(json[0]['userstoryid']);
        	if (json[0]['userstoryid'] == 0)
        		$("#userstoryid").val('');
        	$("#creator").val(json[0]['creator']);
        	$("#type").val(json[0]['type']);
        	$("#status").val(json[0]['status']);
        	$("#priority").val(json[0]['priority']);
        	$("#headline").val(json[0]['headline']);
        	setKEContent('content', json[0]['content']);
    	}
    	else {
        	$("#msg").text("<?= $this->translate('message.common.nodata')?>");
    	}
	});
	if (isEdit) {
		markEnabled(Array("edit"));
		markDisabled(Array("add", "testcaseid"));
	}
	else {
		markDisabled(Array("edit"));
		markEnabled(Array("add", "testcaseid"));
	}
	$("#msg").text("<?= $this->translate('tip.common.action')?>");
	$("#actionPanel").show();
	location.href = "#top";
}

/* Open execution dialog */
function goExecute(obj) {
	var dataRow = $(obj).parent().parent().children();
	var param = "testcaseid=" + dataRow.eq(0).text();
	var url = "<?= Zend_Registry::get('baseUrl')?>/testcase/result";
	$.post(url, param, function (data) {
		var json = eval(data);
    	var lenJson = json.length;
    	if (lenJson > 1) {
        	$("#testcaseid").val(json[0]['testcaseid']);
        	$("#userstoryid").val(json[0]['userstoryid']);
        	if (json[0]['userstoryid'] == 0)
        		$("#userstoryid").val('');
        	$("#creator").val(json[0]['creator']);
        	$("#type").val(json[0]['type']);
        	$("#status").val(json[0]['status']);
        	$("#priority").val(json[0]['priority']);
        	$("#headline").val(json[0]['headline']);
        	setKEContent('content', json[0]['content']);

        	$("#platform").val(json[1]['platform']);
        	$("#version").val(json[1]['version']);
        	$("#result").val(json[1]['result']);
        	$("#comment").val(json[1]['comment']);
    	}
    	else {
    		$("#testcaseid").val(json[0]['testcaseid']);
        	$("#userstoryid").val(json[0]['userstoryid']);
        	if (json[0]['userstoryid'] == 0)
        		$("#userstoryid").val('');
        	$("#creator").val(json[0]['creator']);
        	$("#type").val(json[0]['type']);
        	$("#priority").val(json[0]['priority']);
        	$("#headline").val(json[0]['headline']);
        	setKEContent('content', json[0]['content']);
    	}
	});
	$("#execPlatform").show();
	$("#execResult").show();
	markEnabled(Array("execute"));
	markDisabled(Array("add", "edit", "testcaseid"));
}

/* Execute a test case */
function doExecute() {
	var url = "<?= Zend_Registry::get('baseUrl')?>/execution/add";
	var param = "testcaseid=" + $.trim($("#testcaseid").val()) +
				"&platform=" + $.trim($("#platform").val()) +
				"&version=" + $.trim($("#version").val()) +
				"&result=" + $.trim($("#result").val()) + 
				"&comment=" + $.trim($("#comment").val());
	$.post(url, param, function (data) {
    	switch (data) {
    	case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.add')?>");
    		break;
    	case "result_exist":
    		$("#msg").text("<?= $this->translate('message.execution.result.exist')?>");
    		$("#headline").focus();
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.add.failed')?>" + "Null");
    		break;
    	default:
    		fillData(initUrl, initParam, columnName, operate, currentPage);
    		$("#msg").text("<?= $this->translate('message.common.add.successful')?>" + data);
    	}
    });

	if ($("#result").val() == "Failed") {
		if(!confirm("<?= $this->translate('message.testcase.result.failed')?>"))
			return false;
		location.href = "<?= Zend_Registry::get('baseUrl')?>/defect/index/source/Testcase-" + $.trim($("#testcaseid").val());
	}
}

/* Add new data */
function doAdd() {
	var content = replaceAmp(KE.util.getData('content'));
    if (isNull("headline")) {
		$("#msg").text("<?= $this->translate('message.testcase.headline.null')?>");
		return false;
	}
    if ($.trim(content) == "") {
		$("#msg").text("<?= $this->translate('message.testcase.content.null')?>");
		KE.util.focus('content');
		return false;
	}
	var url = "<?= Zend_Registry::get('baseUrl')?>/testcase/add";
	var param = "userstoryid=" + $.trim($("#userstoryid").val()) + 
				"&type=" + $.trim($("#type").val()) + 
				"&status=" + $.trim($("#status").val()) + 
				"&priority=" + $.trim($("#priority").val()) + 
				"&headline=" + $.trim($("#headline").val()) + 
				"&content=" + content;
    $.post(url, param, function (data) {
    	switch (data) {
    	case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.add')?>");
    		break;
    	case "testcase_exist":
    		$("#msg").text("<?= $this->translate('message.testcase.headline.exist')?>");
    		$("#headline").focus();
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.add.failed')?>" + "Null");
    		break;
    	default:
    		fillData(initUrl, initParam, columnName, operate, currentPage);
    		$("#testcaseid").val(data);
    		$("#msg").text("<?= $this->translate('message.common.add.successful')?>" + data);
    	}
    });
}

/* Edit existing data */
function doEdit() {
	var content = replaceAmp(KE.util.getData('content'));
	if (isNull("headline")) {
		$("#msg").text("<?= $this->translate('message.testcase.headline.null')?>");
		return false;
	}
    if ($.trim(content) == "") {
		$("#msg").text("<?= $this->translate('message.testcase.content.null')?>");
		KE.util.focus('content');
		return false;
	}
    var testcaseid = $.trim($("#testcaseid").val());
	var url = "<?= Zend_Registry::get('baseUrl')?>/testcase/edit";
	var param = "testcaseid=" + testcaseid + 
				"&userstoryid=" + $.trim($("#userstoryid").val()) + 
				"&type=" + $.trim($("#type").val()) + 
				"&status=" + $.trim($("#status").val()) + 
				"&priority=" + $.trim($("#priority").val()) + 
				"&headline=" + $.trim($("#headline").val()) + 
				"&content=" + content;
    $.post(url, param, function (data) {
    	switch (data) {
    	case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.edit')?>");
    		break;
    	case "testcase_exist":
    		$("#msg").text("<?= $this->translate('message.testcase.headline.exist')?>");
    		$("#headline").focus();
    		break;
    	case "1":
    		fillEdit(initUrl, "testcaseid=" + testcaseid, columnName, testcaseid);
    		$("#msg").text("<?= $this->translate('message.common.edit.successful')?>" + $("#testcaseid").val());
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.edit.failed')?>" + $("#testcaseid").val());
    		break;
        default:
    		$("#msg").text(data);
    	}
	});
}

/* Delete data according to ID */
function doDelete(obj) {
	if(!confirm("<?= $this->translate('message.common.delete.confirm')?>"))
		return false;
	var dataRow = $(obj).parent().parent().children();
	var testcaseid = $.trim(dataRow.eq(0).text());
	url = "<?= Zend_Registry::get('baseUrl')?>/testcase/delete";
	param = "testcaseid=" + testcaseid;
	$.post(url, param, function(data) {
		switch (data) {
		case "no_permission":
    		$("#msg").text("<?= $this->translate('message.common.noperm.delete')?>");
    		break;
    	case "1":
    		$("#msg").text("<?= $this->translate('message.common.delete.successful')?>" + testcaseid);
			dataRow.remove();
			$("#totalRecord").text($("#totalRecord").text() - 1);
    		break;
    	case "error":
    		$("#msg").text("<?= $this->translate('message.common.delete.failed')?>" + testcaseid);
    		break;
    	default:
    		$("#msg").text(data);
    	}
	});
}

/* Search data */
function doSearch(isSearch, currentPage) {
	if (isSearch) {
		$("#cacheDiv").removeData("cacheData");
		var cacheArray = new Array();
		cacheArray['testcaseid'] = $.trim($("#testcaseid").val());
		cacheArray['userstoryid'] = $.trim($("#userstoryid").val());
		cacheArray['creator'] = $.trim($("#creator").val());
		cacheArray['type'] = $.trim($("#type").val());
		cacheArray['status'] = $.trim($("#status").val());
		cacheArray['priority'] = $.trim($("#priority").val());
		cacheArray['headline'] = $.trim($("#headline").val());
		cacheArray['content'] = replaceAmp($.trim(KE.util.getPureData('content')));
		$("#cacheDiv").data("cacheData", cacheArray);
	}
	var cacheData = $("#cacheDiv").data("cacheData");
	if (typeof(cacheData) == "undefined")
		var param = "currentpage=" + currentPage;
	else
		var param = "currentpage=" + currentPage +
				"&testcaseid=" + cacheData['testcaseid'] + 
		    	"&userstoryid=" + cacheData['userstoryid'] + 
		    	"&creator=" + cacheData['creator'] +
		    	"&type=" + cacheData['type'] +
		    	"&status=" + cacheData['status'] +
		    	"&priority=" + cacheData['priority'] +
		    	"&headline=" + cacheData['headline'] +
		    	"&content=" + cacheData['content'];
	fillData(initUrl, param, columnName, operate, currentPage);
	$("#msg").text("<?= $this->translate('tip.common.action')?>");
}

/* Reset KE content */
function resetKE() {
	setKEContent("content", "");
}
</script>

<br />
<table class="table-action">
<thead>
<tr>
	<a name="top"></a>
	<td colspan="5">
	    <?= $this->translate('common.page.panel')?>:&nbsp;&nbsp;
	    <label id="hideShow" />
	</td>
</tr>
</thead>
<tbody id="actionPanel">
<tr>
	<td width="14%"><?= $this->translate('column.common.id')?>:</td>
	<td width="36%"><input type="text" id="testcaseid" class="short" title="<?= $this->translate('tip.common.forsearch')?>" /></td>
	<td width="15%"><?= $this->translate('column.testcase.creator')?>:</td>
	<td width="25%" align="right"><input type="text" id="creator" value="<?= $_SESSION['userName']?>" class="short" title="<?= $this->translate('tip.common.forsearch')?>" /></td>
	<td width="10%"></td>
</tr>
<tr>
	<td><?= $this->translate('column.testcase.userstory')?>:</td>
	<td>
	<select id="userstoryid" class="short">
		<option value=""></option>
		<?php
			$common = new Common();
	        foreach ($this->userstory as $userstory) {
	            if ($userstory['userstoryid'] == $this->userstoryid)
	               echo '<option value="' , $userstory['userstoryid'] , '" selected>' , $userstory['userstoryid'] , ' - ' , $common->subString($userstory['headline'], 26) , '</option>';
	            else 
	                echo '<option value="' , $userstory['userstoryid'] , '">' , $userstory['userstoryid'] , ' - ' , $common->subString($userstory['headline'], 26) , '</option>';
	        }
		?>
	</select>
	</td>
	<td><?= $this->translate('column.testcase.type')?>:</td>
	<td align="right">
	<select id="type" class="short">
		<option value=""></option>
			<?php
	        $common = new Common();
	        $tcType = $common->parseDefinition('testcase-type');
		    foreach ($tcType as $tt) {
                echo '<option value="' , $tt , '">' , $tt , '</option>';
		    }
	    ?>
	</select>
	</td>
	<td></td>
</tr>
<tr>
	<td><?= $this->translate('column.testcase.priority')?>:</td>
	<td>
	<select id="priority" class="short">
		<option value=""></option>
			<?php
	        $common = new Common();
	        $tcPriority = $common->parseDefinition('testcase-priority');
		    foreach ($tcPriority as $tp) {
                echo '<option value="' , $tp , '">' , $tp , '</option>';
		    }
	    ?>
	</select>
	</td>
	<td><?= $this->translate('column.testcase.status')?>:</td>
	<td align="right">
	<select id="status" class="short">
		<option value=""></option>
			<?php
	        $common = new Common();
	        $tcStatus = $common->parseDefinition('testcase-status');
		    foreach ($tcStatus as $ts) {
                echo '<option value="' , $ts , '">' , $ts , '</option>';
		    }
	    ?>
	</select>
	</td>
	<td></td>
</tr>
<tr>
	<td><?= $this->translate('column.testcase.headline')?>:</td>
	<td colspan="3"><input type="text" id="headline" maxlength="250" class="long" /></td>
	<td></td>
</tr>
<tr>
	<td><?= $this->translate('column.testcase.content')?>:</td>
	<td colspan="3"><textarea id="content" class="long"></textarea></td>
	<td></td>
</tr>
<tr id="execPlatform" style="display: none">
	<td><?= $this->translate('column.execution.platform')?>:</td>
	<td>
	<select id="platform" class="short">
		<?php
	        foreach ($this->platform as $platform) {
	            echo '<option value="' , $platform['pfname'] , '">' , $platform['pfname'] , '</option>';
	        }
		?>
	</select>
	</td>
	<td><?= $this->translate('column.execution.version')?>:</td>
	<td align="right">
	<select id="version" class="short">
		<?php
	        foreach ($this->version as $version) {
	        	$versionBuild = $version['version'] . '.' . $version['build'];
	            echo '<option value="' , $versionBuild , '">' , $versionBuild , '</option>';
	        }
		?>
	</select>
	</td>
	<td></td>
</tr>
<tr id="execResult" style="display: none">
	<td><?= $this->translate('column.execution.result')?>:</td>
	<td>
	<select id="result" class="short">
	<?php
		$common = new Common();
	    $testResult = $common->parseDefinition('test-result');
		foreach ($testResult as $tr) {
            echo '<option value="' , $tr , '">' , $tr , '</option>';
		}
	?>
	</select>
	</td>
	<td><?= $this->translate('column.execution.comment')?>:</td>
	<td align="right"><input type="text" id="comment" class="short" /></td>
	<td></td>
</tr>
</tbody>
<tfoot>
<tr>
	<td><?= $this->translate('common.page.operate')?>:</td>
	<td>
	<span id="actionButton"></span>&nbsp;
	<input type="button" id="execute" value="<?= $this->translate('common.button.execute')?>" onclick="doExecute()" />
	</td>
	<td colspan="3">
		<span id="msg" class="message"><?= $this->translate('tip.common.action')?></span>
		<span id="loading" class="loading"><img src="<?= Zend_Registry::get('baseDir')?>/Common/Image/loading.gif" /></span>
	</td>
</tr>
</tfoot>
</table>

<br />
<table class="table-data" id="dataTable">
<thead>
<tr>
    <th width="8%" class="id"><?= $this->translate('column.common.id')?></th>
    <th width="35%"><?= $this->translate('column.testcase.headline')?></th>
    <th width="15%"><?= $this->translate('column.testcase.creator')?></th>
    <th width="12%"><?= $this->translate('column.testcase.userstory')?></th>
    <th width="10%"><?= $this->translate('column.testcase.priority')?></th>
    <th width="20%"><?= $this->translate('column.common.operate')?></th>
</tr>
</thead>
<tbody id="dataPanel"></tbody>
<tfoot id="footer"></tfoot>
</table>