<html>
<head>
<title><?= ($_SESSION['goAdmin']=='true') ? 'AgileOne - System Administrator' : 'AgileOne - Power to Agile Development'?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="Keywords" content="AgileOne, Agile Development, Agile Software Management" />
<link rel="stylesheet" type="text/css" href="<?= Zend_Registry::get('baseDir')?>/Common/Layout/Default.css" />
<script language="JavaScript" type="text/javascript" src="<?= Zend_Registry::get('baseDir')?>/Library/JQuery/jquery.js"></script>
<script language="JavaScript" type="text/javascript" src="<?= Zend_Registry::get('baseDir')?>/Library/JQuery/jquery.tablesorter.js"></script>
<script language="JavaScript" type="text/javascript" src="<?= Zend_Registry::get('baseDir')?>/Library/JQuery/jquery.datetime.js"></script>
<script language="JavaScript" type="text/javascript" src="<?= Zend_Registry::get('baseDir')?>/Library/JQuery/jquery.ajaxfileupload.js"></script>
<script language="JavaScript" type="text/javascript" src="<?= Zend_Registry::get('baseDir')?>/Library/KindEditor/kindeditor.js"></script>
<script language="JavaScript">
$(document).ready(function() {
/*******************************************************************/
	/* Define the common ajax global settings */
	$.ajaxSetup({
		  global: true,
		  cache: false,
		  //ifModified: true,
		  type: "POST"
	});
	$("#msg").ajaxSend(function(){
		$(this).hide();
		$("#loading").show();
	});
	$("#msg").ajaxComplete(function(){
		$(this).show();
		$("#loading").hide();
	});
	$("#msg").ajaxError(function(){
		$(this).show();
		$(this).text("<?= $this->translate('message.common.error')?>");
		$("#loading").hide();
	});
	
	/* Common helper for page */
	$("#hideShow").text("<?= $this->translate('common.button.hide')?>");
	$("#edit").attr("disabled","disabled");
	var abHtml = "<input type='button' id='add' onclick='doAdd()' value='<?= $this->translate('common.button.add')?>' />&nbsp;&nbsp;";
	abHtml += "<input type='button' id='edit' onclick='doEdit()' value='<?= $this->translate('common.button.edit')?>' />&nbsp;&nbsp;";
	abHtml += "<input type='button' id='search' onclick='doSearch(true, 1)' value='<?= $this->translate('common.button.search')?>' />&nbsp;&nbsp;";
	abHtml += "<input type='button' id='reset' value='<?= $this->translate('common.button.reset')?>' />";
	$("#actionButton").html(abHtml);

	/* Hide/Show/Reset the edit panel */
	$("#hideShow").toggle(
		function() {
			$("table.table-action tbody").hide();
			$("table.table-action tfoot").hide();
			$("#hideShow").text("<?= $this->translate('common.button.show')?>");
		},
		function() {
			$("table.table-action tbody").show();
			$("table.table-action tfoot").show();
			$("#hideShow").text("<?= $this->translate('common.button.hide')?>");
		});
	$("#reset").click(
		function() {
			$("input[type='text']").val("");
			$("input[type='text']").attr("disabled", false);
			$("#edit").attr("disabled", true);
			$("#add").attr("disabled", false);
			$("input[type=checkbox]").attr("checked", false);
			$("select").val("");
			$("textarea").val("");
			resetKE();
		});
	
	/* Output the welcome message */
	var date = new Date();
	var hour = date.getHours();
	var welcome = "";
	if (hour >= 5 && hour < 12)
		welcome = "<?= $this->translate('common.page.morning')?>: ";
	else if (hour >= 12 && hour < 18)
		welcome = "<?= $this->translate('common.page.afternoon')?>: ";
	else
		welcome = "<?= $this->translate('common.page.evening')?>: ";
	$("#welcome").html(welcome + "<?= $_SESSION['userRole'] . ' ' . $_SESSION['userName']?>");

	/* Initialize the table sorter */
	$("#dataTable").tablesorter({widthFixed: true});

	/* Clear the client cache to retrieve all data */
	$("#cacheDiv").removeData("cacheData");
});

/********************************************************************/

/* Check is Null or not for a string */			
function isNull(id) {
	if ($.trim($("#" + id).val()) == '') {
		$("#" + id).focus();
		return true;
	}
	return false;
}

/* Check is a Number or not */
function isNumber(id) {
	if (isNaN($.trim($("#" + id).val()))) {
		$("#" + id).focus();
		return false;
	} else {
		return true;
	}
}

/* Check is a Datetime format yyyy-mm-dd hh:mm:ss */
function isDateTime(id) {
	var str = $.trim($("#" + id).val());
    var reg = /^(\d{1,4})(-|\/)(\d{1,2})\2(\d{1,2}) (\d{1,2}):(\d{1,2}):(\d{1,2})$/; 
    var r = str.match(reg); 
    if(r==null) {
    	$("#" + id).focus();
        return false;
    }
    var d= new Date(r[1], r[3]-1,r[4],r[5],r[6],r[7]); 
    if (d.getFullYear()==r[1]&&(d.getMonth()+1)==r[3]&&d.getDate()==r[4]&&d.getHours()==r[5]&&d.getMinutes()==r[6]&&d.getSeconds()==r[7]) {
        return true;
    } else {
    	$("#" + id).focus();
        return false;
    }
}

/* Check is a Date format yyyy-mm-dd */
function isDate(id) {
	var str = $.trim($("#" + id).val());
	var reg = /^(\d{1,4})(-|\/)(\d{1,2})\2(\d{1,2})$/; 
    var r = str.match(reg); 
    if(r==null) {
    	$("#" + id).focus();
        return false;
    }
    var d= new Date(r[1], r[3]-1,r[4]); 
    if (d.getFullYear()==r[1]&&(d.getMonth()+1)==r[3]&&d.getDate()==r[4]) {
        return true;
    } else {
    	$("#" + id).focus();
        return false;
    }
}

/* Mark elements disabled */
function markDisabled(elementArray) {
	var len = elementArray.length;
	for (i = 0; i < len; i++) {
		$("#" + elementArray[i]).attr("disabled", true);
	}
}

/* Mark elements enabled */
function markEnabled(elementArray) {
	var len = elementArray.length;
	for (i = 0; i < len; i++) {
		$("#" + elementArray[i]).attr("disabled", false);
	}
}

/* Ajax request for json data */
function fillData(url, param, columnName, operate, currentPage) {
	$.ajax({
		url: url,
		data: param,
		success: function(data) {
			var json = eval(data);
	    	var lenJson = json.length - 1;
	    	var lenColumn = columnName.length;
	    	var totalRecord = json[lenJson]['totalRecord'];
	    	var bodyData = "";
	    	if (lenJson > 0) {
    	    	for(i = 0; i < lenJson; i++)
    	    	{
    	    		bodyData += "<tr id='dtrow_" + json[i][columnName[0]] + "'>";
    	    		bodyData += "<td style='padding-left: 20px;'><label onclick=goEdit(this,false)>" + json[i][columnName[0]] + "</label></td>";
    		    	for (j = 1; j < lenColumn; j++)
    		    		bodyData += "<td>" + json[i][columnName[j]] + "</td>";
	    			if ($.trim(operate) != "") {
	    				bodyData += "<td>";
    	    			if (operate.indexOf("edit") != -1)
    	    				bodyData += "<label onclick='goEdit(this,true)'><?= $this->translate('common.button.edit')?></label>&nbsp;&nbsp;";
            	    	if (operate.indexOf("delete") != -1)
            	    		bodyData += "<label onclick='doDelete(this)'><?= $this->translate('common.button.delete')?></label>&nbsp;&nbsp;";
            	    	if (operate.indexOf("newus") != -1)
            	    		bodyData += "<label onclick='newUserStory(this)'><?= $this->translate('common.button.newus')?></label>&nbsp;&nbsp;";
            	    	if (operate.indexOf("newspec") != -1)
            	    		bodyData += "<label onclick='newSpecification(this)'><?= $this->translate('common.button.newspec')?></label>&nbsp;&nbsp;";
            	    	if (operate.indexOf("newtc") != -1)
            	    		bodyData += "<label onclick='newTestCase(this)'><?= $this->translate('common.button.newtc')?></label>&nbsp;&nbsp;";
            	    	if (operate.indexOf("execute") != -1)
            	    		bodyData += "<label onclick='goExecute(this)'><?= $this->translate('common.button.execute')?></label>&nbsp;&nbsp;";
            	    	bodyData += "</td>";
	    			}
	    			bodyData += "</tr>";
    	    	}
	    	}
	    	else {
	    		bodyData += "<tr><td colspan='4' align='center'><?= $this->translate('message.common.nodata')?></td></tr>";
		    	$("#msg").text("<?= $this->translate('tip.common.action')?>");
	    	}
	    	$("#dataPanel").html(bodyData);
	    	$("#dataTable").trigger("update");

			/* Fill footer with paginator and toper */
			var pageNumber = Math.ceil(totalRecord / <?= Zend_Registry::get('config')->pager->size?>);
			var colspan = ($.trim(operate) != "") ? lenColumn : (lenColumn-1);
			var footerData = "<tr><td colspan='" + colspan + "'>";
				footerData += "<strong><?= $this->translate('common.page.total')?>:&nbsp;&nbsp;<span id='totalRecord'>" + totalRecord + "</span>&nbsp;&nbsp;&nbsp;&nbsp;";
				footerData += "<?= $this->translate('common.page.pagenumber')?>:&nbsp;&nbsp;" + currentPage + " / " + pageNumber + "</strong>&nbsp;&nbsp;&nbsp;&nbsp;";
				footerData += "<img src=<?= Zend_Registry::get('baseDir')?>/Common/Image/first.gif onclick=gotoPage('first',null) />&nbsp;";
				footerData += "<img src=<?= Zend_Registry::get('baseDir')?>/Common/Image/prev.gif onclick=gotoPage('previous',null) />&nbsp;&nbsp;";
				footerData += "<input type='text' id='currentPage' class='pager' value='" + currentPage + "' onkeydown=\"if(event.keyCode==13) gotoPage('goto'," + pageNumber + ")\" />&nbsp;&nbsp;";
				footerData += "<img src=<?= Zend_Registry::get('baseDir')?>/Common/Image/next.gif onclick=gotoPage('next'," + pageNumber + ") />&nbsp;";
				footerData += "<img src=<?= Zend_Registry::get('baseDir')?>/Common/Image/last.gif onclick=gotoPage('last'," + pageNumber + ") />";
				footerData += "<td align='right'><a href='#top'><strong><?= $this->translate('common.page.top')?></strong></a>";
			$("#footer").html(footerData);
		}
	});
}

/* Fill data to updated row */
function fillEdit(url, param, columnName, rowId) {
	$.post(url, param, function(data) {
		var json = eval(data);
		var lenJson = json.length - 1;
	    var lenColumn = columnName.length;
	    if (lenJson == 1) {
	    	updatedRow = $("#dtrow_" + rowId).children();
	    	for (i = 1; i < lenColumn; i++)
	    		updatedRow.eq(i).html(json[0][columnName[i]]);
	    }
	});
}

/* Go to the specified page */
function gotoPage(position, pageNumber) {
	var currentPageNumber = parseInt($("#currentPage").val());
	switch (position) {
	case "first":
		doSearch(false, 1);
		break;
	case "previous":
		if (currentPageNumber - 1 <= 0)
			previousPage = 1;
		else
			previousPage = currentPageNumber - 1;
		doSearch(false, previousPage);
		break;
	case "next":
		if (currentPageNumber + 1 > pageNumber)
			nextPage = currentPageNumber;
		else
			nextPage = currentPageNumber + 1;
		doSearch(false, nextPage);
		break;
	case "last":
		doSearch(false, pageNumber);
		break;
	case "goto":
		if (! isNumber("currentPage"))
			currentPageNumber = 1;
		else if (currentPageNumber <= 0)
			currentPageNumber = 1;
		else if (currentPageNumber > pageNumber)
			currentPageNumber = pageNumber;
		doSearch(false, currentPageNumber);
		break;
	default:
		doSearch(false, 1);
	}
}

/* Go to set current project */
function gotoProj() {
	var url = "<?= Zend_Registry::get('baseUrl')?>/common/chproj";
	var param = "projectid=" + $.trim($("#myproject").val()) + 
			"&projname=" + $("#myproject option[selected]").text();
	$.post(url, param, function (data) {
		location.href = "<?= Zend_Registry::get('baseUrl')?>";
	});
}

/* Create a new item */
function newItem() {
	var module = $("#newitem").val();
	location.href = "<?= Zend_Registry::get('baseUrl')?>/" + module;
}

/* For KindEditor to set content use */
function setKEContent(id, content) {
	KE.g[id].iframeDoc.open();
    KE.g[id].iframeDoc.write(KE.util.getFullHtml(id));
    KE.g[id].iframeDoc.close();
    KE.g[id].newTextarea.value = '';
    KE.util.focus(id);
    KE.util.selection(id);
    KE.util.insertHtml(id, content);
}

/* Replace & with AGILE14U from any input area,
 * Because Jquery use & to separate parameter,
 * And it will be replaced back to & on PHP side
*/
function replaceAmp(string) {
	return string.replace(/&/g, "AGILE14U");
}

</script>
</head>
<body scroll="no">
<div id="cacheDiv"></div>
<table class="layout-table">
<tr class="header">
<td class="header-logo">
	<a href="<?= ($_SESSION['goAdmin'] == 'true') ? (Zend_Registry::get('baseUrl') . '/admin') : Zend_Registry::get('baseUrl')?>"><img src="<?= Zend_Registry::get('baseDir')?>/Common/Image/agileone.gif" /></a>
</td>
<td class="header-menu">
	<img src="<?= Zend_Registry::get('baseDir')?>/Common/Image/welcome.gif" />&nbsp;
	<span id="welcome" style="color: #FFFFFF"></span>&nbsp;&nbsp;&nbsp;&nbsp;
	<a href="<?= ($_SESSION['goAdmin'] == 'true') ? Zend_Registry::get('baseUrl') . '/admin' : Zend_Registry::get('baseUrl')?>/common/chlang/locale/en" style="color: #FFFFFF"><?= $this->translate('common.page.english')?></a>&nbsp;&nbsp;
	<a href="<?= ($_SESSION['goAdmin'] == 'true') ? Zend_Registry::get('baseUrl') . '/admin' : Zend_Registry::get('baseUrl')?>/common/chlang/locale/zh" style="color: #FFFFFF"><?= $this->translate('common.page.chinese')?></a>&nbsp;&nbsp;
	<?php 
	    if ($_SESSION['goAdmin'] == 'true')
	        echo '<a href="' , Zend_Registry::get('baseUrl') , '/admin/common/exitadmin" style="color: #FFFFFF">' , $this->translate('admin.page.exit') , '</a>&nbsp;&nbsp;';
	    else
	    {
	        echo '<a href="' , Zend_Registry::get('baseUrl') , '/prefer" style="color: #FFFFFF">' , $this->translate('common.page.preference') , '</a>&nbsp;&nbsp;';
	        if ($_SESSION['userRole'] == 'Administrator')
	            echo '<a href="' , Zend_Registry::get('baseUrl') , '/common/goadmin" style="color: #FFFFFF">' , $this->translate('admin.page.admin') , '</a>&nbsp;&nbsp;';
	    }	        
	?>
	<a href="<?= Zend_Registry::get('baseUrl')?>/common/logout" style="color: #FFFFFF"><?= $this->translate('common.page.logout')?></a>
</td>
</tr>
<tr>
<td class="left">
	<div class="left-menu"><ul>
	<?php 
		$common = new Common();
		if ($_SESSION['goAdmin'] == 'true') {
		    $content = $common->parseNavigator('admin');
    		foreach ($content as $key=>$value) {
    			if (strpos($_SERVER['PHP_SELF'], $key) > 0)
                	echo '<li style="background-color: #6BC4E0;"><a href="' , Zend_Registry::get('baseUrl') , '/' , $key , '">' , $this->translate("$value") , '</a></li>';
                else 
                	echo '<li><a href="' , Zend_Registry::get('baseUrl') , '/' , $key , '">' , $this->translate("$value") , '</a></li>';
            }
		}
		else {
		    $content = $common->parseNavigator('menu');
            foreach ($content as $key=>$value) {
                if (Permission::isAllowed($key, 'query')) {
                	if (strpos($_SERVER['PHP_SELF'], $key) > 0)
                    	echo '<li style="background-color: #6BC4E0;"><a href="' , Zend_Registry::get('baseUrl') , '/' , $key , '">' , $this->translate("$value") , '</a></li>';
                    else 
                    	echo '<li><a href="' , Zend_Registry::get('baseUrl') , '/' , $key , '">' , $this->translate("$value") , '</a></li>';
                }
            }
		}
	?>
	</ul></div>
	<div class="left-bottom">
		Copyright&copy; <a href="http://www.woniuxy.com/" target="_blank">Woniuxy.COM</a><br />
		Power by <a href="http://framework.zend.com" target="_blank">ZendFramework</a>
	</div>
</td>
<td style="100%">
<div class="content">
	<a name="top"></a>
	<?php if ($_SESSION['goAdmin'] != 'true') {?>
	<div class="content-top">
	<div class="content-top-proj">
		<?= $this->translate('common.page.myproj')?>:&nbsp;
        <select id="myproject">
    	<?php 
    	    $myProject = $_SESSION['myProject'];
    	    foreach ($myProject as $value) {
    	        if ($_SESSION['currentProjectId'] == $value['projectid'])
    	            echo '<option value="' , $value['projectid'] , '" selected>' , $value['projname'], '</option>';
    	        else
    	            echo '<option value="' , $value['projectid'] , '">' , $value['projname'], '</option>';
    	    }
    	?>
    	</select>&nbsp;
    	<input type="button" onclick="gotoProj()" value="<?= $this->translate('common.button.goto')?>" />
	</div>
	<div class="content-top-new">
    	<?= $this->translate('common.page.newitem')?>:&nbsp;
    	<select id="newitem">
    	<?php 
    		$common = new Common();
            $content = $common->parseNavigator('new');
            foreach ($content as $key=>$value) {
                echo '<option value="' , $key , '">' , $this->translate("$value") , '</option>';
            }
        ?>
    	</select>&nbsp;
    	<input type="button" onclick="newItem()" value="<?= $this->translate('common.button.new')?>" />
	</div>
	</div>
	<?php } ?>
	<div class="content-main">
		<?= $this->layout()->content ?>
	</div>
	<!-- 
	<div class="content-bottom">
    	<a href="#"><?= $this->translate('common.page.about')?></a>&nbsp;&nbsp;
    	<a href="#"><?= $this->translate('common.page.contact')?></a>&nbsp;&nbsp;
    	<a href="#"><?= $this->translate('common.page.advice')?></a>&nbsp;&nbsp;
    	<a href="#"><?= $this->translate('common.page.license')?></a>&nbsp;&nbsp;
    	<a href="#"><?= $this->translate('common.page.guide')?></a>&nbsp;&nbsp;
    	Copyright &copy; AgileOne.NET
    </div>
     -->
</div>
</td>
</tr>
</table>
</body>
</html>
